### ISSUE TITLE
Edit Login | Register Form widget > Add style settings for Remember me & Forgot password?

### ISSUE THREAD

**Issue by FlyThePlanet** [WPDevelopers/essential-addons-for-elementor-lite#727]
The Edit Login | Register Form widget has a looot of settings, but surprisingly 2 fields have been forgotten:
- the Remember me checkbox
- and the Forgot password? hyperlink

For example, we can't change the border color for the Remember Me checkbox when we hover it.
Or we can't change color and hover color for the Forgot password? hyperlink.

It's really not convenient as we can style all the rest of the widget, but we are stuck with inappropriate colors for only 2 fields and we need to go via custom CSS to fix the issue 👎 
https://wordpress.org/support/topic/edit-login-register-form-widget-customize-remember-me-lost-password/#post-15725959

So could you please add those missing settings?
Thanks!

**Comment by amitbarai013** [comment]
Hi @FlyThePlanet,
Currently, we don’t have an option for changing the Remember Me checkbox and Forgot Password hover color.

However, you will be able to do this using custom CSS. I forwarded the message to the developer team. Hope this feature will be implemented in the next few releases.

Thank you.
Have a good day!

**Comment by amitbarai013** [comment]
Hi @FlyThePlanet,
Hope you are doing well.

We are glad to inform you that this issue has been fixed in one of our developer versions of the **Essential Addons for Elementor** plugin. Please download the plugin from here: https://d.pr/f/zsrnlc

Let me know how it goes.
Thank you.

**Comment by FlyThePlanet** [comment]
Hi,

Yep, just tested it and it looks like it works fine.
Thanks!

Waiting for the fix of the 2nd issue now...
https://github.com/WPDevelopers/essential-addons-for-elementor-lite/issues/728

**Comment by amitbarai013** [comment]
Hi @FlyThePlanet,
Thanks for letting us know the update.

We are glad to know that it worked on your end.

Have a good day! :)

**Comment by FlyThePlanet** [comment]
Closed but still not released!
It was not in the 5.1.9 yesterday :-/

**Comment by FlyThePlanet** [comment]
Hi,

Ok, this time it's delivered and it works!
You can close the ticket.
Thanks.

It's just a bit a pity that the fix was developed and successfully tested in 2 weeks mid June, but had to wait 3 months 1/2 to be released.

**Comment by abid112** [comment]
Hi @FlyThePlanet , Really sorry for this delayed. Since other issues/implementations were on the same branch, hence it took time. 

I’m closing this issue. Thanks for confirming this.
